export const JOB_TRIGGER_DAILY_MONITORING_DEADLINE = 'TRIGGER_DAILY_MONITORING_DEADLINE';

export const JOB_TRIGGER_DAILY_MONITORING_INITIALIZATION =
  'TRIGGER_DAILY_MONITORING_INITIALIZATION';

export const JOB_CLEAN_COMPLETED_JOBS = 'CLEAN_COMPLETED_JOBS';

export const JOB_GENERATE_TASK_TICKET_JOB = 'GENERATE_TASK_TICKET_JOB';

export const JOB_GENERATE_LATE_TASK_REMINDER_JOB = 'GENERATE_LATE_TASK_REMINDER_JOB';

export const JOB_GENERATE_ALERT_JOB = 'GENERATE_ALERT_JOB';

export const JOB_SET_FARMINGCYCLE_INPROGRESS = 'SET_FARMINGCYCLE_INPROGRESS';

export const JOB_TRIGGER_IOT_DEVICE_ALERT = 'TRIGGER_IOT_DEVICE_ALERT';

export const JOB_TRIGGER_IOT_DEVICE_OFFLINE = 'TRIGGER_IOT_DEVICE_OFFLINE';

export const QUEUE_PUSH_NOTIFICATION = 'push-notification';

export const QUEUE_GAMIFICATION_TASK_SUBMITTED = 'GAMIFICATION_TASK_SUBMITTED';

export const QUEUE_GAMIFICATION_TASK_POINT = 'GAMIFICATION_TASK_POINT';

export const QUEUE_GAMIFICATION_TASK_VERIFIED = 'GAMIFICATION_TASK_VERIFIED';

export const QUEUE_REPEATABLE_JOB = 'REPEATABLE_JOB';

export const QUEUE_USER_OWNER_UPDATED = 'USER_OWNER_UPDATED';

export const QUEUE_FARM_UPDATED = 'FARM_UPDATED';

export const QUEUE_COOP_UPDATED = 'COOP_UPDATED';

export const QUEUE_FARMING_CYCLE_CREATED = 'FARMING_CYCLE_CREATED';

export const QUEUE_FARMING_CYCLE_CLOSED = 'FARMING_CYCLE_CLOSED';

export const QUEUE_FARMING_CYCLE_CREATED_FMS = 'FARMING_CYCLE_CREATED_FMS';

export const QUEUE_PURCHASE_REQUEST_CREATED = 'PURCHASE_REQUEST_CREATED';

export const QUEUE_PURCHASE_REQUEST_APPROVED = 'PURCHASE_REQUEST_APPROVED';

export const QUEUE_CALCULATE_DAILY_MONITORING = 'CALCULATE_DAILY_MONITORING';

export const QUEUE_INITIALIZE_DAILY_MONITORING = 'INITIALIZE_DAILY_MONITORING';

export const QUEUE_FINALIZE_DAILY_MONITORING = 'FINALIZE_DAILY_MONITORING';

export const QUEUE_CHICKIN_REQUEST_CREATED = 'CHICKIN_REQUEST_CREATED';

export const QUEUE_CHICKIN_REQUEST_UPDATED = 'CHICKIN_REQUEST_UPDATED';

export const QUEUE_CHICKIN_REQUEST_APPROVED = 'CHICKIN_REQUEST_APPROVED';

export const QUEUE_TRANSFER_REQUEST_CREATED = 'TRANSFER_REQUEST_CREATED';

export const QUEUE_TRANSFER_REQUEST_APPROVED = 'TRANSFER_REQUEST_APPROVED';

export const QUEUE_TRANSFER_REQUEST_CANCEL = 'TRANSFER_REQUEST_CANCEL';

export const QUEUE_GOODS_RECEIPT_CREATED = 'GOODS_RECEIPT_CREATED';

export const QUEUE_PURCHASE_ORDER_APPROVED = 'PURCHASE_ORDER_APPROVED';

export const QUEUE_REINDEX_ERP_PRODUCTS = 'REINDEX_ERP_PRODUCTS';

export const QUEUE_FARMING_CYCLE_DOC_IN = 'FARMING_CYCLE_DOC_IN';

export const QUEUE_REPOPULATION_CREATED = 'REPOPULATION_CREATED';

export const QUEUE_SELF_REGISTRATION = 'SELF_REGISTRATION';

export const QUEUE_NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';

export const QUEUE_HARVEST_REQUEST_APPROVED = 'HARVEST_REQUEST_APPROVED';

export const QUEUE_HARVEST_REQUEST_CANCELLED = 'HARVEST_REQUEST_CANCELLED';

export const QUEUE_HARVEST_REQUEST_EDITED = 'HARVEST_REQUEST_EDITED';

export const QUEUE_HARVEST_REQUEST_REJECTED = 'HARVEST_REQUEST_REJECTED';

export const QUEUE_HARVEST_REQUEST_SUBMITTED = 'HARVEST_REQUEST_SUBMITTED';

export const QUEUE_HARVEST_REALIZATION_SUBMITTED = 'HARVEST_REALIZATION_SUBMITTED';

export const QUEUE_HARVEST_DEAL_CREATED = 'HARVEST_DEAL_CREATED';

export const QUEUE_USER_ASSIGNED_TO_FC = 'USER_ASSIGNED_TO_FC';

export const QUEUE_ISSUE_CREATED = 'ISSUE_CREATED';

export const QUEUE_TASK_TICKET_ALERT_CREATED = 'TASK_TICKET_ALERT_CREATED';

export const QUEUE_TASK_TICKET_DETAIL_UPDATED = 'TASK_TICKET_DETAIL_UPDATED';

export const QUEUE_GENERATE_DOCUMENT = 'GENERATE_DOCUMENT';

export const QUEUE_GENERATE_TASK_TICKET = 'GENERATE_TASK_TICKET';

export const QUEUE_GENERATE_LATE_TASK_REMINDER = 'GENERATE_LATE_TASK_REMINDER';

export const QUEUE_CONTRACT_CREATED = 'CONTRACT_CREATED';

export const QUEUE_CONTRACT_UPDATED = 'CONTRACT_UPDATED';

export const QUEUE_GENERATE_ALERT = 'GENERATE_ALERT';

export const QUEUE_SET_IOT_DEVICE_STATUS = 'SET_IOT_DEVICE_STATUS';

export const QUEUE_GENERATE_IOT_DEVICE_ALERT = 'GENERATE_IOT_DEVICE_ALERT';

export const QUEUE_IOT_SMART_CONVENTRON_CREATED = 'CREATE_IOT_SMART_CONVENTRON';
