version: "2"

services:
  kafka-0:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    volumes:
      - kafka_0_data:/bitnami/kafka
    networks:
      - kafka
  kafka-1:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9093:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
    volumes:
      - kafka_1_data:/bitnami/kafka
    networks:
      - kafka
  kafka-2:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9094:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka-0:9093,1@kafka-1:9093,2@kafka-2:9093
      - KAFKA_KRAFT_CLUSTER_ID=abcdefghijklmnopqrstuv
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9094
    volumes:
      - kafka_2_data:/bitnami/kafka
    networks:
      - kafka

volumes:
  kafka_0_data:
    driver: local
  kafka_1_data:
    driver: local
  kafka_2_data:
    driver: local

networks:
  kafka:
    driver: bridge
