export const whitelist: Record<string, string[]> = {
  superadmin: ["*"],
  developer: ["/", "/master/*", "/farm-operation/*", "/report/*"],
  technician: ["/", "/master/*", "/farm-operation/*", "/report/*"],
  admin: ["/", "/master/*", "/farm-operation/*", "/report/*"],
  "sales admin": ["/", "/report/harvest", "/report/harvest/*"],
  "mitra manager": [
    "/",
    "/master/*",
    "/farm-operation/*",
    "/report/*",
    "/iot",
    "/iot/*",
  ],
  "business unit": ["/", "/master/*", "/farm-operation/*", "/report/*"],
  "kawan KSO": ["/", "/master/*", "/farm-operation/*", "/report/*"],
  "poultry leader": ["/", "/master/*", "/farm-operation/*", "/report/*"],
  "poultry worker": ["/", "/master/*", "/farm-operation/*", "/report/*"],
  internal: ["/", "/master/*", "/farm-operation/*", "/report/*"],
  "system integrator": ["/", "/master/*", "/farm-operation/*", "/report/*"],
  odoo: ["/", "/master/*", "/farm-operation/*", "/report/*"],
  operational: ["/", "/master/*", "/farm-operation/*", "/report/*"],
  "pembantu umum": [
    "/",
    "/master/*",
    "/farm-operation/*",
    "/report/*",
    "/iot",
    "/iot/*",
  ],
  "area manager": [
    "/",
    "/master/*",
    "/farm-operation/*",
    "/report/*",
    "/iot",
    "/iot/*",
  ],
  "general manager": [
    "/",
    "/master/*",
    "/farm-operation/*",
    "/report/*",
    "/iot",
    "/iot/*",
  ],
  "vice president": [
    "/",
    "/master/*",
    "/farm-operation/*",
    "/report/*",
    "/iot",
    "/iot/*",
  ],
  "c level": ["/", "/master/*", "/farm-operation/*", "/report/*"],
  owner: ["/", "/master/*", "/farm-operation/*", "/report/*"],
  ppl: ["/", "/master/*", "/farm-operation/*", "/report/*", "/iot", "/iot/*"],

  itsupport: ["/", "/iot", "/iot/*"],
  adminiot: ["/", "/iot", "/iot/*"],
  iotoperations: ["/", "/iot", "/iot/*"],
  superadminiot: [
    "/",
    "/master/user/internal",
    "/master/user/internal/*",
    "/iot",
    "/iot/*",
    "/master/farm-data/farm",
    "/master/farm-data/building",
    "/master/farm-data/room",
    "/master/farm-data/coop",
  ],
};
