/* eslint-disable no-unused-vars */
export enum TaskTicketDetailEventsEnum {
  TICKET_DETAIL_UPDATED = 'TICKET_DETAIL_UPDATED ',
}

export enum IssueEventsEnum {
  ISSUE_CREATED = 'ISSUE_CREATED',
}

export enum TaskTicketEventsEnum {
  TASK_TICKET_ALERT_CREATED = 'TASK_TICKET_ALERT_CREATED',
}

export enum FCMemberEventsEnum {
  USER_ASSIGNED_TO_FC = 'USER_ASSIGNED_TO_FC',
}

export enum HarvestRequestEventsEnum {
  HARVEST_REQUEST_SUBMITTED = 'HARVEST_REQUEST_SUBMITTED',
  HARVEST_REQUEST_EDITED = 'HARVEST_REQUEST_EDITED',
  HARVEST_REQUEST_APPROVED = 'HARVEST_REQUEST_APPROVED',
  HARVEST_REQUEST_REJECTED = 'HARVEST_REQUEST_REJECTED',
  HARVEST_REQUEST_CANCELLED = 'HARVEST_REQUEST_CANCELLED',
}

export enum HarvestDealEventsEnum {
  HARVEST_DEAL_CREATED = 'HARVEST_DEAL_CREATED',
}

export enum HarvestRealizationEventsEnum {
  HARVEST_REALIZATION_SUBMITTED = 'HARVEST_REALIZATION_SUBMITTED',
}
